# Generated by Django 3.1 on 2020-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150)),
                ("link", models.URLField(max_length=250)),
                ("created", models.DateField(auto_now_add=True)),
                ("upvotes", models.IntegerField(default=0)),
                ("author_name", models.CharField(max_length=50)),
            ],
        ),
    ]
